### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by roulito** [Txuritan/EiraIRC#2]
As soon as you receive a message from chat twitch or send a message on chat twitch from the EiraIRC interface

---- Minecraft Crash Report ----
WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.62-dev-78.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.2-anarchy.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 6/10/17 2:42 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at net.blay09.mods.eirairc.util.Utils.addMessageToChat(Utils.java:50)
	at net.blay09.mods.eirairc.EiraIRC$1.addChatMessage(EiraIRC.java:89)
	at net.blay09.mods.eirairc.EiraIRC$1.addChatMessage(EiraIRC.java:81)
	at net.blay09.mods.eirairc.handler.MCEventHandler.onClientChat(MCEventHandler.java:161)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_MCEventHandler_onClientChat_ClientChatEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.blay09.mods.eirairc.client.gui.chat.GuiChatExtension.keyTyped(GuiChatExtension.java:197)
	at net.blay09.mods.eirairc.client.gui.chat.GuiChatExtended.func_73869_a(GuiChatExtended.java:59)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:569)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1695)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.blay09.mods.eirairc.util.Utils.addMessageToChat(Utils.java:50)
	at net.blay09.mods.eirairc.EiraIRC$1.addChatMessage(EiraIRC.java:89)
	at net.blay09.mods.eirairc.EiraIRC$1.addChatMessage(EiraIRC.java:81)
	at net.blay09.mods.eirairc.handler.MCEventHandler.onClientChat(MCEventHandler.java:161)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_MCEventHandler_onClientChat_ClientChatEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.blay09.mods.eirairc.client.gui.chat.GuiChatExtension.keyTyped(GuiChatExtension.java:197)
	at net.blay09.mods.eirairc.client.gui.chat.GuiChatExtended.func_73869_a(GuiChatExtended.java:59)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:569)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)

-- Affected screen --
Details:
	Screen name: net.blay09.mods.eirairc.client.gui.chat.GuiChatExtended

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 266445264 bytes (254 MB) / 531296256 bytes (506 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.38 Powered by Forge 13.20.0.2284 Optifine OptiFine_1.11.2_HD_U_B7 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2284.jar) 
	UCHIJA	forge{13.20.0.2284} [Minecraft Forge] (forge-1.11.2-13.20.0.2284.jar) 
	UCHIJA	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIJA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHIJA	eirairc{5.0.0} [EiraIRC] (eirairc-mc1.11.2-5.0.0.jar) 
	UCHIJA	foamfix{@VERSION@} [FoamFix] (foamfix-0.6.2-anarchy.jar) 
	UCHIJA	hud{1.3.8} [Better HUD] (hud-1.3.8-1.11.jar) 
	UCHIJA	inventorytweaks{1.62-dev-78-e073cca} [Inventory Tweaks] (InventoryTweaks-1.62-dev-78.jar) 
	UCHIJA	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCHIJA	llor{1.1.3-mc1.11.2} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.3-mc1.11.2.jar) 
	UCHIJA	lunatriuscore{1.1.2.39} [LunatriusCore] (LunatriusCore-1.11.jar) 
	UCHIJA	schematica{1.7.8.157} [Schematica] (Schematica-1.11-1.7.8.157-universal.jar) 
	UCHIJA	chunkbase_slimemod_ssp{2.1} [Slime Mod (SSP)] (SlimeModSSP-1.11-2.1.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.62-dev-78.jar)
  invtweaks.forge.asm.ContainerTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.1008' Renderer: 'AMD Radeon HD 5800 Series'
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2284
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 5800 Series GL version 4.5.13399 Compatibility Profile Context 15.201.1151.1008, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [1.9.2]Dramatic Skys [v1.6].zip (incompatible), Sama_Faithful v1.2 [Minecraft 1.11.x].zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM)2 Quad CPU Q9650 @ 3.00GHz
	OptiFine Version: OptiFine_1.11.2_HD_U_B7
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13399 Compatibility Profile Context 15.201.1151.1008
	OpenGlRenderer: AMD Radeon HD 5800 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by Txuritan** [comment]
The problem was solved with versions 5.0.1 and 5.0.2, 5.0.2 can be downloaded [here](https://minecraft.curseforge.com/projects/devotion-irc/)
