### ISSUE TITLE
Cannot reload config or connect to server on dedicated servers

### ISSUE THREAD

**Issue by SinZ163** [Txuritan/EiraIRC#3]
Minecraft version 1.12.2
Mod version: 5.0.3
```
> sirc config reload
[16:28:51] [Server thread/INFO]: Reloading config from file...
[16:28:52] [IRC (esper)/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
[16:28:52] [IRC (esper)/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:   at net.blay09.mods.eirairc.util.Utils.addMessageToChat(Utils.java:59)
[16:28:52] [IRC (esper)/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:   at net.blay09.mods.eirairc.EiraIRC$1.addChatMessage(EiraIRC.java:89)
[16:28:53] [IRC (esper)/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:   at net.blay09.mods.eirairc.EiraIRC$1.addChatMessage(EiraIRC.java:81)
[16:28:53] [IRC (esper)/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:   at net.blay09.mods.eirairc.util.ChatComponentBuilder.send(ChatComponentBuilder.java:57)
[16:28:53] [IRC (esper)/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:   at net.blay09.mods.eirairc.util.ChatComponentBuilder.send(ChatComponentBuilder.java:46)
[16:28:53] [IRC (esper)/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:   at net.blay09.mods.eirairc.handler.IRCEventHandler.fireConnectionFailedEvent(IRCEventHandler.java:381)
[16:28:53] [IRC (esper)/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:   at net.blay09.mods.eirairc.irc.IRCConnectionImpl.run(IRCConnectionImpl.java:223)
[16:28:53] [IRC (esper)/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:   at java.lang.Thread.run(Unknown Source)
[16:28:53] [IRC (irc.esper.net)/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
[16:28:53] [IRC (irc.esper.net)/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:   at net.blay09.mods.eirairc.util.Utils.addMessageToChat(Utils.java:59)
[16:28:53] [IRC (irc.esper.net)/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:   at net.blay09.mods.eirairc.EiraIRC$1.addChatMessage(EiraIRC.java:89)
[16:28:53] [IRC (irc.esper.net)/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:   at net.blay09.mods.eirairc.EiraIRC$1.addChatMessage(EiraIRC.java:81)
[16:28:53] [IRC (irc.esper.net)/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:   at net.blay09.mods.eirairc.handler.IRCEventHandler.firePrivateChatEvent(IRCEventHandler.java:201)
[16:28:53] [IRC (irc.esper.net)/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:   at net.blay09.mods.eirairc.irc.IRCConnectionImpl.handleMessage(IRCConnectionImpl.java:505)
[16:28:53] [IRC (irc.esper.net)/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:   at net.blay09.mods.eirairc.irc.IRCConnectionImpl.run(IRCConnectionImpl.java:236)
[16:28:53] [IRC (irc.esper.net)/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:   at java.lang.Thread.run(Unknown Source)
```

https://github.com/Txuritan/EiraIRC/blob/f8214561332a5810ffe446b9c7eceec6480a2dc0/src/main/java/net/blay09/mods/eirairc/util/Utils.java#L49-L65

**Comment by Txuritan** [comment]
This has been fixed with version 5.0.4.

See: d6f3dae239943bf5ca47ded1ea69a138787537de

**Comment by SinZ163** [comment]
Where can I get 5.0.4, jenkins link points to old maintainer and curseforge is also old maintainer, and you haven't done a github release for the new version

**Comment by Txuritan** [comment]
I release it on the [Devotion IRC](https://minecraft.curseforge.com/projects/devotion-irc) page on CurseForge.
